{
 "title": "平台监控",
 "description": "平台监控",
 "tags": [ "iot" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d"
   },
   {
    "name": "env",
    "label": "环境",
    "query": "label_values(node_exporter_build_info,env)"
   },
   {
    "name": "name",
    "label": "主机名",
    "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
   },
   {
    "name": "node",
    "label": "系统节点",
    "query": "label_values(node_exporter_build_info{name=~'$name'},instance)"
   },
   {
    "name": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
   },
   {
    "name": "ip",
    "label": "平台节点",
    "query": "label_values(node,exported_instance)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "系统监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "运行时间",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "erlang_vm_statistics_wallclock_time_milliseconds{ exported_instance = \"$ip\" } / 1000"
    }
   ]
  },
  {
   "title": "CPU 核数",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100"
    }
   ]
  },
  {
   "title": "CPU使用率（5m）",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU iowait（5m）",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "ETS表使用",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "erlang_vm_ets_tables{ exported_instance = \"$ip\" } / erlang_vm_ets_limit{ exported_instance = \"$ip\" } * 100"
    }
   ]
  },
  {
   "title": "进程数使用",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "erlang_vm_process_count{ exported_instance = \"$ip\" } / erlang_vm_process_limit{ exported_instance = \"$ip\" } * 100"
    }
   ]
  },
  {
   "title": "端口使用",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 19, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "erlang_vm_port_count{ exported_instance = \"$ip\" } / erlang_vm_port_limit{ exported_instance = \"$ip\" } * 100"
    }
   ]
  },
  {
   "title": "当前打开的文件描述符",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "内存容量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": " node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "系统平均负载",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=~\"$node\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=~\"$node\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "系统内存信息",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "总内存"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "已用"
    }
   ]
  },
  {
   "title": "平台内存使用情况",
   "type": "graph",
   "description": "Erlang系统统计",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_memory_processes_bytes_total{ exported_instance = \"$ip\", usage = \"used\" } / 1024 / 1024",
     "legendFormat": "Processes"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{ exported_instance = \"$ip\", usage = \"ets\" } / 1024 / 1024",
     "legendFormat": "ETS"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{ exported_instance = \"$ip\", usage = \"atom\" } / 1024 / 1024",
     "legendFormat": "Atom"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{ exported_instance = \"$ip\", usage = \"code\" } / 1024 / 1024",
     "legendFormat": "Code"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{ exported_instance = \"$ip\", usage = \"binary\" } / 1024 / 1024",
     "legendFormat": "Binary"
    },
    {
     "expr": "node{ exported_instance = \"$ip\", key = \"used_memory\" } / 1024 / 1024",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU使用率、磁盘每秒的I/O操作耗费时间（%）",
   "type": "graph",
   "description": "node_disk_io_time_seconds_total：\n磁盘花费在输入/输出操作上的毫秒数。该值为累加值。（Milliseconds Spent Doing I/Os）\n\nirate(node_disk_io_time_seconds_total[1m])：\n计算每秒的速率：(last值-last前一个值)/时间戳差值，即：1秒钟内磁盘花费在I/O操作的时间占比。",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[1m])) by (instance)",
     "legendFormat": "System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[1m])) by (instance)",
     "legendFormat": "User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[1m])) by (instance)",
     "legendFormat": "Iowait"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_每秒I/O操作"
    }
   ]
  },
  {
   "title": "TCP 连接情况",
   "type": "graph",
   "description": "CurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n\nActiveOpens - 已从 CLOSED 状态直接转换到 SYN-SENT 状态的 TCP 平均连接数(1分钟内)\n\nPassiveOpens - 已从 LISTEN 状态直接转换到 SYN-RCVD 状态的 TCP 平均连接数(1分钟内)\n\nTCP_alloc - 已分配（已建立、已申请到sk_buff）的TCP套接字数量\n\nTCP_inuse - 正在使用（正在侦听）的TCP套接字数量\n\nTCP_tw - 等待关闭的TCP连接数",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
     "legendFormat": "ESTABLISHED"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~'$node'}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=~'$node'}[1m])",
     "legendFormat": "ActiveOpens"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=~'$node'}[1m])",
     "legendFormat": "PassiveOpens"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~'$node'}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=~'$node'}",
     "legendFormat": "TCP_inuse"
    }
   ]
  },
  {
   "title": "网络流量",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "bps", "label": "上传（-）/下载（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])*8",
     "legendFormat": "{{device}}_in下载"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])*8",
     "legendFormat": "{{device}}_out上传"
    }
   ]
  },
  {
   "title": "磁盘IO读写时间",
   "type": "graph",
   "description": "Read time ms 每个磁盘分区读操作花费的秒数\n\nWrite time ms 每个磁盘分区写操作花费的秒数\n\nIO time ms 每个磁盘分区输入/输出操作花费的秒数\n\nIO time weighted 每个磁盘分区输入/输出操作花费的加权秒数",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_读取"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_写入"
    }
   ]
  },
  {
   "title": "磁盘读写容量大小",
   "type": "graph",
   "description": "Read bytes 每个磁盘分区每秒读取的比特数\nWritten bytes 每个磁盘分区每秒写入的比特数",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "Bps", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_读取"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_写入"
    }
   ]
  },
  {
   "title": "磁盘读写速率（IOPS）",
   "type": "graph",
   "description": "Reads completed: 每个磁盘分区每秒读完成次数\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "iops", "label": "读取（-）/写入（+）I/O ops/sec" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_读取"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_写入"
    }
   ]
  }
 ]
}